### ISSUE TITLE
Interesting project - it bypasses some the complexity of VRTK

### ISSUE THREAD

**Issue by andybak** [AlexHolderDeveloper/BigfootXR#1]
VRTK's use of the vendor SDKs leads to a lot of awkwardness - proxy controllers, headset cameras that are disabled on scene start (which can break other scripts) etc. I like the approach here although you are limited by the current incomplete state of the Unity SDK support. I'm guessing no haptics are possible yet for example.

Do you have a roadmap for future features?

Have you investigated whether some of the code from VRTK could be incorporated into this? The bezier pointers spring to mind as they would vastly improve the teleporting functionality you currently have.

**Comment by AlexHolderDeveloper** [comment]
Thankyou Andy, VRTK totally slipped my mind when uploading this. Ideally yes, VRTK's reliance on vendor SDKs will be the big difference to this and its reliance on the Unity built-in XR support. It is very likely that this will limit features such as haptics, for sure.

Honestly I haven't thought very far ahead with this yet. This was uploaded to test things out on Github - as you can probably notice, this is my first repo. Roadmap will be priority since I didn't expect people to find this just yet. I'm happily surprised at least =) 

Improved teleporting & different types of teleport visualization are definitely planned. The content in BigfootVRTK is based on an "intro to VR dev" workshop I ran recently - no fancy content, just enough to get people started so far. 

I think I might need to rename this too - "BigfootVRTK" seems a lil too close to VRTK for my comfort. Maybe BigfootXR would work? ;)

**Comment by Vytek** [comment]
Very interesting!
A similar project I think is: https://github.com/ololralph/vrsandboxgame
You can integrate Hands Models?
